package commentnotifier

import "strings"

var zhCN = map[string]string{
	"Send email notifications when a comment is posted or approved.": "在评论发布或审核通过后发送邮件提醒。",
	"Comment Email Notifications":                                    "评论邮件提醒",
	"General":                                                        "基本设置",
	"Enable email notifications":                                     "启用邮件提醒",
	"Notify content author":                                          "通知内容作者",
	"Notify the person being replied to":                             "通知被回复者",
	"Notify admin of pending comments":                               "待审核评论通知管理员",
	"Admin recipient email":                                          "管理员收件邮箱",
	"Email address for receiving pending comment notifications.":     "用于接收待审核评论通知的邮箱地址。",
	"SMTP Server":                                                    "SMTP 服务器",
	"SMTP Port":                                                      "SMTP 端口",
	"SMTP Security":                                                  "SMTP 加密模式",
	"No encryption":                                                  "无安全加密",
	"SSL encryption":                                                 "SSL加密",
	"TLS encryption":                                                 "TLS加密",
	"SMTP Username":                                                  "SMTP 用户名",
	"SMTP password or authorization code":                            "SMTP 密码或授权码",
	"Usually the SMTP authorization code generated by your email provider, not the web login password.": "通常应填写邮箱服务商生成的 SMTP 授权码，而不是网页登录密码。",
	"Sender email":   "发件邮箱",
	"Sender name":    "发件人名称",
	"Sender":         "发件人",
	"Test email settings":                          "测试邮件设置",
	"Send a test email using the saved SMTP parameters": "使用已经保存的 SMTP 参数发送一封测试邮件",
	"SMTP configuration is incomplete; comment email notifications will not be sent.": "SMTP 配置尚未填写完整，评论邮件提醒当前不会发送邮件。",

	"Your post \"%s\" has a new comment":   "你的《%s》文章有了新的评论",
	"Your comment on [%s] has a new reply": "你在[%s]的评论有了新的回复",
	"Post \"%s\" has a pending comment":    "文章《%s》有条待审评论",
	"GopherInk Comment Notification":       "GopherInk 评论通知",

	"View comment":                          "查看评论",
	"Comment":                               "评论",
	"Your post received a new comment":      "你的文章收到了新评论",
	"%s commented on your post \"%s\".":     "%s 在《%s》发表了新评论。",
	"Your comment received a new reply":     "你的评论收到了新回复",
	"%s replied to your comment on \"%s\".": "%s 回复了你在《%s》下的评论。",
	"View reply":                            "查看回复",
	"Reply":                                 "回复",
	"There is a comment pending review":     "有待审核的评论",
	"\"%s\" received a comment awaiting review.": "《%s》收到一条等待审核的评论。",
	"Go to review":                          "前往审核",
	"Email send test":                       "邮件发送测试",
	"This is a test email to verify SMTP configuration and email appearance.": "这是一封用于验证 SMTP 配置和邮件外观的测试邮件。",
	"Visit site":    "访问站点",
	"Test content":  "测试内容",
	"Your previous comment:": "你此前的评论：",

	"Notification type: owner, guest, pending, or test": "通知类型：owner、guest、pending 或 test",
	"Notification headline":                              "通知标题",
	"Summary generated based on notification type":       "根据通知类型生成的摘要",
	"Site name":                                          "站点名称",
	"Site URL":                                           "站点地址",
	"Post or page title":                                 "文章或页面标题",
	"Link to the comment location":                       "评论所在位置的链接",
	"Recipient name":                                     "收件人名称",
	"Commenter name":                                     "评论者名称",
	"Avatar URL for commenter email":                     "评论者邮箱对应的头像地址",
	"Comment, reply, or test content label":              "评论、回复或测试内容标签",
	"Comment body":                                       "评论正文",
	"Comment time":                                       "评论时间",
	"Parent commenter name":                              "被回复者名称",
	"Avatar URL for parent commenter email":              "被回复者邮箱对应的头像地址",
	"Parent comment body":                                "被回复的评论正文",
	"Original comment block in reply notifications; empty for other types": "回复通知中的原评论区块，其他通知为空",
	"URL to view the comment or go to review":           "查看评论或前往审核的地址",
	"Action button text":                                "操作按钮文本",

	"Available Placeholders": "可用占位符",
	"Comment content and other external data are automatically HTML-escaped. Inline CSS and JavaScript in the template are written as-is into the email; actual support depends on the recipient's email client.": "评论内容等外部数据会自动进行 HTML 转义。模板中的内嵌 CSS 和 JavaScript 会原样写入邮件，实际支持情况由收件客户端决定。",
	"Edit":                   "编辑",
	"Preview":                "预览",
	"Email template view mode": "邮件模板查看模式",
	"HTML email template":    "HTML 邮件模板",
	"Email template preview": "邮件模板预览",
	"Save settings":          "保存设置",
	"Restore default":        "恢复默认",
	"Customize email notification appearance": "自定义邮件提醒外观",
	"Comment email appearance":                "评论邮件外观",
	"Adjust the HTML template for comment notification emails and preview the effect in real time.": "调整评论通知邮件的 HTML 模板并即时预览效果。",

	"unknown plugin page: %s":          "未知的插件页面：%s",
	"Visitor":                          "访客",
	"A post for previewing email styles": "一篇用于预览邮件样式的文章",
	"New commenter":                    "新评论者",
	"This is the reply content.\nPlaceholders will be rendered with mock data in real time.": "这是回复内容。\n占位符会使用模拟数据即时渲染。",
	"This is the original comment content.": "这是原评论内容。",
	"generate email preview data: %w":  "生成邮件预览数据：%w",
	"render email appearance settings: %w": "渲染邮件外观设置：%w",
	"Email template cannot be empty; to restore the built-in template, use \"Restore default\"": "邮件模板不能为空；如需恢复内置模板，请使用\u201c恢复默认\u201d",
	"Email template cannot exceed 48 KiB": "邮件模板不能超过 48 KiB",
	"Email appearance settings saved.":     "邮件外观设置已保存。",
	"Email appearance has been restored to the default template.": "邮件外观已恢复为默认模板。",
	"Unsupported email appearance action":  "不支持的邮件外观操作",

	"unknown plugin action: %s":     "未知的插件操作：%s",
	"unable to read plugin config: %w": "无法读取插件配置：%w",
	"invalid SMTP configuration: %w":   "SMTP 配置无效：%w",
	"[GopherInk] Email send test":      "[GopherInk] 邮件发送测试",
	"Admin":                             "管理员",
	"Email appearance preview":          "邮件外观预览",
	"If you received this email, the SMTP configuration and current email template are working correctly.": "如果你收到了这封邮件，说明 SMTP 配置和当前邮件模板可以正常工作。",
	"unable to render test email: %w":  "无法渲染测试邮件：%w",
	"test email send failed: %w":       "测试邮件发送失败：%w",
	"Test email has been sent to %s.":  "测试邮件已发送至 %s。",
}

func T(lang, key string) string {
	key = strings.TrimSpace(key)
	if key == "" {
		return ""
	}
	if strings.EqualFold(lang, "zh-CN") || strings.EqualFold(lang, "zh_CN") || strings.HasPrefix(strings.ToLower(lang), "zh") {
		if value := strings.TrimSpace(zhCN[key]); value != "" {
			return value
		}
	}
	return key
}
