package commentnotifier

import (
	"context"
	"strings"

	"github.com/Chocola-X/GopherInk/core/plugin"
)

const pluginName = "comment-notifier"

type commentNotifier struct{}

func init() { plugin.Register(commentNotifier{}) }

func (commentNotifier) Name() string    { return pluginName }
func (commentNotifier) Version() string { return "0.2.1" }
func (commentNotifier) Description() string {
	return "Send email notifications when a comment is posted or approved."
}

func (commentNotifier) Info() plugin.PluginInfo {
	return plugin.PluginInfo{
		Name:             pluginName,
		Version:          "0.2.1",
		Description:      "Send email notifications when a comment is posted or approved.",
		RequireGopherInk: "0.5.0",
	}
}

func (commentNotifier) Init(m *plugin.Manager) {
	m.RegisterRuntimeHook(plugin.HookCommentAfterSave, afterCommentSave)
	m.RegisterRuntimeHook(plugin.HookCommentAfterMark, afterCommentMark)
	m.RegisterAdminMenu(plugin.AdminMenuItem{
		Label: "Comment Email Notifications",
		URL:   "/admin/plugins/" + pluginName + "/config",
		Icon:  "mail",
	})
}

func (commentNotifier) ConfigSchema() []plugin.FieldSchema {
	return []plugin.FieldSchema{
		{Name: "enabled", Label: "Enable email notifications", Group: "General", Type: plugin.FieldCheckbox, Default: "1"},
		{Name: "notify_owner", Label: "Notify content author", Group: "General", Type: plugin.FieldCheckbox, Default: "1"},
		{Name: "notify_parent", Label: "Notify the person being replied to", Group: "General", Type: plugin.FieldCheckbox, Default: "1"},
		{Name: "notify_pending", Label: "Notify admin of pending comments", Group: "General", Type: plugin.FieldCheckbox, Default: "1"},
		{Name: "admin_email", Label: "Admin recipient email", Group: "General", Type: plugin.FieldText, Required: true, Wide: true,
			Description: "Email address for receiving pending comment notifications."},
		{Name: "smtp_host", Label: "SMTP Server", Group: "SMTP", Type: plugin.FieldText, Required: true, Wide: true, Default: "smtp.qq.com"},
		{Name: "smtp_port", Label: "SMTP Port", Group: "SMTP", Type: plugin.FieldNumber, Default: "465", Required: true, Min: "1", Max: "65535", Step: "1"},
		{Name: "smtp_security", Label: "SMTP Security", Group: "SMTP", Type: plugin.FieldSelect, Default: "ssl",
			Options: []plugin.FieldOption{
				{Label: "No encryption", Value: "none"},
				{Label: "SSL encryption", Value: "ssl"},
				{Label: "TLS encryption", Value: "tls"},
			},
		},
		{Name: "smtp_username", Label: "SMTP Username", Group: "SMTP", Type: plugin.FieldText, Required: true, Wide: true},
		{Name: "smtp_password", Label: "SMTP password or authorization code", Group: "SMTP", Type: plugin.FieldPassword, Required: true, Wide: true,
			Description: "Usually the SMTP authorization code generated by your email provider, not the web login password."},
		{Name: "from_mail", Label: "Sender email", Group: "Sender", Type: plugin.FieldText, Required: true, Wide: true},
		{Name: "from_name", Label: "Sender name", Group: "Sender", Type: plugin.FieldText, Default: "GopherInk", Wide: true},
	}
}

func (commentNotifier) AdminActions() []plugin.AdminAction {
	return []plugin.AdminAction{{
		Name:        "test-email",
		Label:       "Test email settings",
		Icon:        "send",
		Variant:     "outlined",
		Description: "Send a test email using the saved SMTP parameters",
	}}
}

func (commentNotifier) AdminNotices(_ context.Context, _ *plugin.Runtime, values map[string]string) []plugin.AdminNotice {
	required := []string{"admin_email", "smtp_host", "smtp_username", "smtp_password", "from_mail"}
	for _, name := range required {
		if strings.TrimSpace(values[name]) == "" {
			return []plugin.AdminNotice{{
				Type:    plugin.NoticeWarning,
				Mode:    plugin.NoticeCard,
				Message: "SMTP configuration is incomplete; comment email notifications will not be sent.",
			}}
		}
	}
	return nil
}

func (commentNotifier) Translate(lang, key string) string {
	return T(lang, key)
}
